[package]
name = "aoc2020"
version = "0.1.0"
authors = ["awfa9"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
nom = "6.0"